version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: telegram_medical_data

models:
  - name: medical_transformed
    description: "This model transforms raw medical data by extracting location name after @"
    columns:
      - name: Channel Title
        description: "The name of the channel."
        tests:
          - not_null
          - unique
      - name: StockCode
        description: "Unique code for the advertised stock."
        tests:
          - not_null
      - name: Location
        description: "Location of the product."
        tests:
          - not_null
